apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-llm-models
  namespace: local-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
